services:
  - type: web
    name: ConvoSec_AI-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: ./data/ConvoSec_AI.sqlite
      - key: JWT_SECRET
        sync: false
      - key: CLIENT_ORIGIN
        sync: false
